### ISSUE TITLE
Question about the MSE on the boundary.

### ISSUE THREAD

**Issue by BeteixZ** [erfanhamD/pinn-torch#1]
I'm so thankful for your excellent codes on PINNs. Your idea enlights me a lot!
However, when I want to try some other PDEs, I always failed to calculate the right MSE for the boundary.
For example, I have a PDE written as follows:
![thumbnail_pastedImage](https://user-images.githubusercontent.com/17287792/202249400-7b02d259-195a-4ca6-9bc6-ae7cf9874f9c.png)

It has a Neumann boundary condition so I rewrite your code (from the Schrodingers Equations)

```python
def mse_b(model, t_b):
    ...

    # x_b is the boundary points on +5
    x_b_right = torch.zeros_like(t_b)+5
    x_b_right.requires_grad = True
    # evaluating the function on the right side boundary
    h_b_right = model(torch.stack((x_b_right, t_b), axis = 1))
    # extracting the u and v values from the model output
    h_u_b_right = h_b_right[:, 0]
    h_v_b_right = h_b_right[:, 1]
    # evaluating the derivative of the parameters of the function on the right boundary
    h_u_b_right_x = derivative(h_u_b_right, x_b_right, 1)
    h_v_b_right_x = derivative(h_v_b_right, x_b_right, 1)

    mse_drichlet = (h_u_b_left-h_u_b_right)**2+(h_v_b_left-h_v_b_right)**2
    mse_newman = (h_u_b_left_x-h_u_b_right_x)**2+(h_v_b_left_x-h_v_b_right_x)**2
```

to

```python
x_b_lower = 2*numpy.pi*torch.exp(-t_b)  # as in the equation
x_b_lower.requires_grad = True # doing this make an error, but if I don't track the grad, it fails to converge
u_b_upper = model(torch.stack((x_b_upper, t_b), axis =1)) # get the model's predict
u_x_b_lower = derivative(u_b_lower, x_b_lower,1) # get the 1st order derivative (u_x)
mse_nuemann = ((u_b_lower - u_x_b_lower)**2).mean() # calculate the mse
```

As I write in the comments, I calculate the exact $u_x$ at the first line, but since it's involved calculation, the required_grad property fails since the variable is no longer a leaf of the grad graph, so I delete this line. But it fails to converge at last.

I'm confused about this, can you give me some advice? Thank you so much, I stuck here for days and have no means but to bother you. Again, thank you for your great work!

**Comment by erfanhamdi** [comment]
Hi @BeteixZ 

Glad I was of any help!
Can you also put here what the error is?
Currently, I see two errors in your code; first I don't think that torch has a `torch.pi`, you can use `numpy.pi` instead.
and I believe that you have a typo in writing `requires_grad`

**Comment by BeteixZ** [comment]
@erfanhamdi, Thank you so much for your reply!
I'm sorry I made a typo here, I've edited the post.

The error is:

```
  File "/home/beteix/PINNs/PINN_torch/test2.py", line 98, in mse_b
    x_b_lower.requires_grad = True
RuntimeError: you can only change requires_grad flags of leaf variables.
```

If I set requires_grad to be true to the code:

```
t_x_train = Variable(torch.from_numpy(t_x_train.astype(np.float32)),requires_grad=False).to(device)
```
The error occurs, otherwise, it can run but does not converge.

I upload the notebook and this is the link: 
https://github.com/BeteixZ/PINNs/blob/main/PINN_cont_customized_rev.ipynb

**Comment by BeteixZ** [comment]
I think I made some stupid mistakes on how to construct f and some dimension errors and now I've fixed them. Again, thank you for your detailed codes! 
By the way, the result is highly depended on the activation function of the model, do you have any comment about this? Is this related to the derivative of the activation function?

**Comment by erfanhamdi** [comment]
great!
there is this great article by Karniadakis that has a specific section on the choice of activation functions for PINNs I recommend you read that:
https://arxiv.org/abs/2209.02681

**Comment by BeteixZ** [comment]
Many thanks, I really appreciate that!
